import unittest
import os
from tempfile import gettempdir

from ament_index_python.packages import get_package_share_directory
import maliput.plugin

from maliput_sim.utils.obj import generate_obj_file_from_road_network, get_obj_description_from_road_network


class MaliputToObjTests(unittest.TestCase):
    """Tests for the maliput to obj conversion."""
    _MALIPUT_BACKEND = "maliput_malidrive"
    _TMP_DIR = "/tmp/maliput_sim/test/utils/obj_test"
    _OBJ_FILE = _TMP_DIR + "/road_network.obj"
    _DEFAULT_OBJ_PATH = gettempdir() + "/maliput_sim/road_network.obj"

    def __init__(self, *args):
        super().__init__(*args)
        self._remove_list = []

    def setUp(self):
        maliput_backend_share_dir = get_package_share_directory(self._MALIPUT_BACKEND)
        rn_configuration = {"opendrive_file":
                            maliput_backend_share_dir + "/resources/odr/TShapeRoad.xodr"}
        self._maliput_road_network = maliput.plugin.create_road_network(
            self._MALIPUT_BACKEND, rn_configuration)

    def tearDown(self):
        # Remove the generated obj files.
        for file in self._remove_list:
            os.remove(file)

    def test_generate_obj_file_from_road_network(self):
        obj_filepath = generate_obj_file_from_road_network(self._maliput_road_network, self._TMP_DIR)
        self._remove_list.append(obj_filepath)

        self.assertTrue(os.path.exists(obj_filepath))
        self.assertEqual(obj_filepath, self._OBJ_FILE)

    def test_generate_obj_file_from_road_network_default_out_dir(self):
        obj_filepath = generate_obj_file_from_road_network(self._maliput_road_network)
        self._remove_list.append(obj_filepath)

        self.assertTrue(os.path.exists(obj_filepath))
        self.assertEqual(obj_filepath, self._DEFAULT_OBJ_PATH)

    def test_get_obj_description_from_road_network(self):
        obj_description = get_obj_description_from_road_network(self._maliput_road_network)
        self._remove_list.append(self._DEFAULT_OBJ_PATH)
        self.assertNotEqual(obj_description, '')
        # Read the first line of the obj file description.
        self.assertEqual(obj_description.splitlines()[0], '# GENERATED BY maliput::utility::GenerateObjFile()')
