name: colcon build & test

on:
  push:
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  PACKAGE_NAME: maliput_sim
  ROS_DISTRO: foxy

jobs:
  compile_and_test:
    name: Compile and test
    runs-on: ubuntu-latest
    container:
      image: ubuntu:20.04
    steps:
    - uses: actions/checkout@v3
    - uses: ros-tooling/setup-ros@v0.6
    - name: poetry install
      shell: bash
      run: pip3 install poetry
      # TODO(francocipollone): Once new release is done in colcon-poetry-ros package we can point directly to the official release.
    - name: colcon-poetry-ros install
      shell: bash
      run: pip3 install 'colcon-poetry-ros @ git+https://github.com/UrbanMachine/colcon-poetry-ros@main'
    - name: install package's poetry dependencies
      shell: bash
      run: python3 -m colcon_poetry_ros.dependencies.install --base-paths  ${GITHUB_WORKSPACE}/../
    - uses: ros-tooling/action-ros-ci@v0.3
      id: action_ros_ci_step
      with:
        package-name: ${{ env.PACKAGE_NAME }}
        target-ros2-distro: ${{ env.ROS_DISTRO }}
        vcs-repo-file-url: ${GITHUB_WORKSPACE}/.github/dependencies.repos
